#!/bin/bash -e
#	grmlcustomize - Customize ISO images for the GRML Linux distribution
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of grmlcustomize.
#
#	grmlcustomize is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	grmlcustomize is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with grmlcustomize; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

ROOT_FS_DIR="$1"
ISO_DIR="$2"
CONFIG_DIR="$3"

JBIN_DIR="${ROOT_FS_DIR}/usr/jbin"
cd "${ROOT_FS_DIR}/usr"
if [ ! -d "$JBIN_DIR" ]; then
	git clone https://github.com/johndoe31415/jbin
else
	cd "${JBIN_DIR}"
	git reset --hard origin/master
	git checkout master
	git clean -dfx
	git pull
fi
find "${JBIN_DIR}" -type f -executable -exec chmod 755 {} \+
find "${JBIN_DIR}" -type f '!' -executable -exec chmod 644 {} \+
find "${JBIN_DIR}" -type d -exec chmod 755 {} \+
chmod 755 "${JBIN_DIR}"

cp -r "${JBIN_DIR}/skeleton/." "${ROOT_FS_DIR}/root"
chown -R root:root "${ROOT_FS_DIR}/root"

cp -r "${JBIN_DIR}/skeleton/." "${ROOT_FS_DIR}/home/grml"
UID_GID=`stat -c '%u:%g' "${ROOT_FS_DIR}/home/grml"`
chown -R "$UID_GID" "${ROOT_FS_DIR}/home/grml"
